name: 'Sync Windmill'
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  # schedule:
  #  - cron:  '0 * * * *'

env:
  WMILL_URL: https://app.windmill.dev/
  WMILL_WORKSPACE: github-sync-demo

jobs:
  sync:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Setup wmill
        run: |
          deno run --unstable -A  https://deno.land/x/wmill@v1.67.4/main.ts workspace add __automation ${{ env.WMILL_WORKSPACE }} ${{ env.WMILL_URL }} --token ${{ secrets.WMILL_TOKEN }}
          deno run --unstable -A  https://deno.land/x/wmill@v1.67.4/main.ts sync push --yes --fail-conflicts   
                                                                                                 